# syntax=docker/dockerfile:1

FROM golang:1.21-alpine AS build

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /bin/ingestor ./cmd/ingestor

# Set environment variables
ENV KAFKA_BROKERS=kafka:29092
ENV KAFKA_TOPIC=BTC_USD_JOINED

# Final minimal runtime container
FROM alpine:3.17
WORKDIR /app
COPY --from=build /bin/ingestor /app/
ENTRYPOINT ["/app/ingestor"]
