version: '3'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,INTERNAL://kafka:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CREATE_TOPICS=btc_usd:1:1
    depends_on:
      - zookeeper


  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    container_name: schema-registry
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    depends_on:
      - kafka

  ksqldb-server:
    image: confluentinc/ksqldb-server:latest
    container_name: ksqldb-server
    ports:
      - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: "kafka:29092"
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_SERVICE_ID: "ksql_service_"
      KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_QUERIES_FILE: "/etc/ksql/queries.sql"
      KSQL_QUERIES_AUTO_CREATE_TOPICS: "true"
    volumes:
      - ./ksqldb.sql:/etc/ksql/queries.sql  
    depends_on:
      - kafka
      - schema-registry

  ingestor-service:
    image: ingestor-service:latest
    build:
      context: .
      dockerfile: Dockerfile.ingestor
    container_name: ingestor-service
    environment:
      - KAFKA_BROKERS=kafka:29092
      - KAFKA_TOPIC=BTC_USD_JOINED
    depends_on:
      - kafka

  trader-service:
    image: trader-service:latest
    build:
      context: .
      dockerfile: Dockerfile.trader
    container_name: trader-service
    environment:
      - KAFKA_BROKERS=kafka:29092
      - KAFKA_TOPIC=BTC_USD_JOINED
    depends_on:
      - kafka
      - ksqldb-server
      - ingestor-service

  